package com.andro.domain

import javax.inject.Inject

class CountryInteractor @Inject constructor(
    private val apiRepository: ApiRepository
) {

    suspend fun getEmployeeList() : List<EmployeeModel> =
        apiRepository.getEmployees()

    fun getCountryList(): List<CountryModel> =
        listOf(
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
            CountryModel("https://popperssu.ru/wp-content/uploads/Russia-Flag-PNG-Pic.png", "Country"),
        )
}

data class EmployeeModel(
    val id: Int
)
